[build]
  command = "npm run build" # The command to build your project
  publish = "dist"          # The directory where your build output is located
  functions = "netlify/functions" # Optional: Directory for Netlify Functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Optional: Environment variables
[build.environment]
  NODE_VERSION = "18" # Specify the Node.js version
  REACT_APP_API_URL = "https://cv-tailor-backend.onrender.com/" # Example environment variable

# Optional: Custom headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Optional: Edge functions
[[edge_functions]]
  path = "/api/*"
  function = "my-edge-function"